---

- name: "Include Zabbix gpg ids"
  include_vars: zabbix.yml

- name: "Set some variables"
  set_fact:
    zabbix_short_version: "{{ zabbix_version | regex_replace('\\.', '') }}"
    zabbix_server_apt_repository:
      - "http://repo.zabbix.com/zabbix/{{ zabbix_version }}/{{ ansible_distribution.lower() }}/"
      - "{{ ansible_distribution_release }}"
      - "main"

- name: "Debian | Set some facts"
  set_fact:
    datafiles_path: /usr/share/zabbix-server-{{ zabbix_server_database }}
  when:
    - zabbix_version is version_compare('3.0', '<')
  tags:
    - zabbix-server
    - init
    - config

- name: "Debian | Set some facts for Zabbix 3.0"
  set_fact:
    datafiles_path: /usr/share/doc/zabbix-server-{{ zabbix_server_database }}
  when:
    - zabbix_version is version_compare('3.0', '>=')
  tags:
    - zabbix-server
    - init
    - config

- name: Wait for apt dependency lock
  shell: while fuser /var/lib/dpkg/lock >/dev/null ; do sleep $[ ( $RANDOM % 10 )  + 1 ]s; done
  args:
    executable: /bin/bash

- name: "Debian | Install gpg key"
  apt_key:
    id: "{{ sign_keys[zabbix_short_version][ansible_distribution_release]['sign_key'] }}"
    url: http://repo.zabbix.com/zabbix-official-repo.key
  register: zabbix_server_repo_files_installed
  until: zabbix_server_repo_files_installed is succeeded
  when:
    - zabbix_repo == "zabbix"
  become: yes
  tags:
    - zabbix-server
    - init

- name: "Debian | Installing repository {{ ansible_distribution }}"
  apt_repository:
    repo: "{{ item }} {{ zabbix_server_apt_repository | join(' ') }}"
    state: present
  when: zabbix_repo == "zabbix"
  with_items:
    - deb-src
    - deb
  tags:
    - zabbix-server
    - init

- name: apt-get clean
  shell: apt-get clean; rm -rf /tmp/*; apt-get update
  args:
    warn: False
  changed_when: False
  tags:
    - skip_ansible_lint

- name: "Debian | Installing zabbix-server-{{ zabbix_server_database }}"
  apt:
    pkg: zabbix-server-{{ zabbix_server_database }}
    state: "{{ zabbix_server_package_state }}"
    update_cache: yes
    cache_valid_time: 0
    install_recommends: "{{ zabbix_server_install_recommends }}"
  register: zabbix_server_package_installed
  until: zabbix_server_package_installed is succeeded
  tags:
    - zabbix-server
    - init

- name: "Debian | Install Ansible module dependencies"
  apt:
    name: python-psycopg2
    state: present
  register: zabbix_server_dependencies_installed
  until: zabbix_server_dependencies_installed is succeeded
  when:
    - zabbix_database_creation
  tags:
    - zabbix-server
    - init

- name: "Debian | Install Mysql Client package"
  apt:
    name:
      - mysql-client
      - python-mysqldb
    state: present
  register: zabbix_server_dependencies_installed
  until: zabbix_server_dependencies_installed is succeeded
  when:
    - zabbix_server_database == 'mysql'
    - zabbix_server_install_database_client
  tags:
    - zabbix-server
    - init
    - database

- name: "Debian | Install PostgreSQL Client package"
  apt:
    name: postgresql-client
    state: present
  register: zabbix_server_dependencies_installed
  until: zabbix_server_dependencies_installed is succeeded
  when:
    - zabbix_server_database == 'pgsql'
    - zabbix_server_install_database_client
  tags:
    - zabbix-server
    - init
    - database
